name: Deploy to Lambda using aws-actions/aws-lambda-deploy

on:
  push:
    branches:
      - never
    paths:
      - 'lambda/**'

  workflow_run:
    workflows: ["Deploy Terraform"]
    types:
      - completed
    branches:
      - feature/integration

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build Python Dependencies
        working-directory: ./lambda
        run: |
          pip install -r requirements.txt -t ./package
          cp app.py ./package/

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          aws-region: ${{ vars.REGION }}

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: ${{ vars.LAMBDA_NAME }}
          code-artifacts-dir: lambda/package
          handler: app.lambda_handler
          runtime: python3.11
          publish: true