name: Deploy Single-File Website
on:
  push:
    branches: [main]

env:
  AWS_REGION: ${{ vars.REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # - name: Clear S3 bucket
      #   run: aws s3 rm s3://$S3_BUCKET --recursive

      - name: Upload index.html
        run: aws s3 cp index.html s3://$S3_BUCKET/index.html --acl public-read
