name: Deploy Website
on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ vars.REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      # STEP 1: PRINT THE OIDC TOKEN
      - name: 🔬 Print OIDC Token for Learning
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            core.info('--- OIDC Token ---');
            core.info(token);
            core.info('------------------');

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::544067237869:role/GithubActionsRole
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.REGION }}
          audience: sts.amazonaws.com

      # STEP 2: PRINT THE TEMPORARY AWS CREDENTIALS
      - name: 🔬 Print Temporary AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}"

      - name: Upload index.html
        run: aws s3 cp index.html s3://$S3_BUCKET/index.html --content-type text/html