name: Deploy Application to S3

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'

  # Trigger after the infrastructure workflow completes successfully
  workflow_run:
    workflows: ["Deploy AWS Infrastructure"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::544067237869:role/GithubActionsRole
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.REGION }}
          audience: sts.amazonaws.com

      - name: Upload index.html to S3
        run: |
          aws s3 cp index.html s3://${{ vars.S3_BUCKET_NAME }}/index.html --content-type text/html

  # deploy-oidc:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write # This is required for requesting the JWT
  #     contents: read  # This is required for actions/checkout
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3 # Download a copy of your repo's code onto the runner

  #     # https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-aws
  #     - name: Configure AWS credentials (OIDC)
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: arn:aws:iam::544067237869:role/GithubActionsRole
  #         role-session-name: GitHub_to_AWS_via_FederatedOIDC
  #         aws-region: ${{ vars.REGION }}
  #         audience: sts.amazonaws.com

  #     - name: Upload index.html
  #       run: aws s3 cp index.html s3://$S3_BUCKET/index.html --content-type text/html