name: Deploy with Packer
on:
  push:
    branches:
      - main
    paths:
      - 'packer/**'
env:
  AWS_REGION: ${{ vars.REGION }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::544067237869:role/GithubActionsRole
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.REGION }}
          audience: sts.amazonaws.com

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: 1.11.1

      - name: Run `packer init`
        working-directory: ./packer/demo
        run: "packer init ."

      - name: Run `packer validate`
        working-directory: ./packer/demo
        run: "packer validate ."

      - name: Run `packer build`
        working-directory: ./packer/demo
        run: "packer build ."