name: Deploy Website (Access Keys)
on:
  push:
    branches: [main]
env:
  AWS_REGION: ${{ vars.REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET_NAME }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: aws s3 rm s3://$S3_BUCKET --recursive
      - run: aws s3 sync index.html s3://$S3_BUCKET --delete