name: Deploy with Packer
on:
  push:
    branches:
      - never
    paths:
      - 'packer/**'

env:
  AWS_REGION: ${{ vars.REGION }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    env:
      PKR_VAR_ami_prefix: ${{ vars.AMI_PREFIX }}
      PKR_VAR_packer_vpc_id: ${{ vars.PACKER_VPC_ID }}
      PKR_VAR_packer_subnet_id: ${{ vars.PACKER_SUBNET_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::544067237869:role/GithubActionsRole
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.REGION }}
          audience: sts.amazonaws.com

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: 1.11.1

      - name: Run `packer init`
        working-directory: ./packer/builds/web-app
        run: "packer init ."

      - name: Run `packer validate`
        working-directory: ./packer/builds/web-app
        run: "packer validate ."

      - name: Run `packer build`
        working-directory: ./packer/builds/web-app
        run: "packer build ."